# Generated by cabal2nix from telomare.cabal; regenerate when build-depends
# change:
#
#   nix run nixpkgs#cabal2nix -- --compiler=ghc-9.10.3 . > nix/telomare-cabal2nix.nix
#
# then put `src = ./..;` back. It is checked in because the ekapkgs package
# set does not (yet) carry cabal2nix at the top level, so `callCabal2nix`
# cannot run at evaluation time; a dependency missing here fails `Setup
# configure` loudly, which is the drift check.
{ mkDerivation, aeson, base, binary, bytestring, containers
, cryptonite, data-fix, deepseq, Diff, directory, dlist, filepath
, free, genvalidity, haskeline, hspec, lens, lib, lsp, lsp-types
, megaparsec, memory, mtl, optparse-applicative, pretty-show
, process, QuickCheck, recursion-schemes, stm, strict, tasty
, tasty-hunit, tasty-quickcheck, text, time, transformers
, utf8-string, validity
}:
mkDerivation {
  pname = "telomare";
  version = "0.1.0.0";
  src = ./..;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    base binary bytestring containers cryptonite data-fix deepseq dlist
    filepath free genvalidity lens megaparsec memory mtl
    recursion-schemes transformers utf8-string validity
  ];
  executableHaskellDepends = [
    aeson base containers directory filepath free haskeline lens lsp
    lsp-types megaparsec mtl optparse-applicative process
    recursion-schemes stm strict text time
  ];
  testHaskellDepends = [
    base bytestring containers data-fix Diff free hspec megaparsec mtl
    pretty-show QuickCheck recursion-schemes strict tasty tasty-hunit
    tasty-quickcheck
  ];
  homepage = "https://github.com/Stand-In-Language/stand-in-language#readme";
  description = "A simple but robust virtual machine";
  license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
}
