name:                telomare
version:             0.1.0.0
synopsis:            A simple but robust virtual machine
description:         Please see README.md
homepage:            https://github.com/Stand-In-Language/stand-in-language#readme
license:             Apache-2.0
license-file:        LICENSE
author:              Sam Griffin
maintainer:          sam.griffin@gmail.com
copyright:           2020 Sam Griffin
category:            Language
build-type:          Simple
extra-source-files:  CHANGELOG.md, README.md
cabal-version:       >=1.10

data-files:          Prelude.tel
                   , tictactoe.tel
                   , simpleplus.tel
                   , testchar.tel
                   , tc_ultra_minimal.tel
                   , test/programs/limits/unbounded-input-recursion.tel
                   , test/programs/limits/over-budget-recursion.tel

library
  hs-source-dirs:      src
  other-extensions:    GADTs
                     , EmptyDataDecls
                     , DeriveFunctor
                     , FlexibleContexts
                     , ScopedTypeVariables
                     , OverloadedStrings
                     , RecursiveDo
                     , LambdaCase
  exposed-modules:     Telomare.Artifact
                     , Telomare.Certificate
                     , Telomare.Desugar
                     , Telomare.Error
                     , Telomare.Eval
                     , Telomare.Fast
                     , Telomare.IR.Base
                     , Telomare.IR.Builder
                     , Telomare.IR.Core
                     , Telomare.IR.Loc
                     , Telomare.IR.Surface
                     , Telomare.IR.Types
                     , Telomare.Levels
                     , Telomare.Meter
                     , Telomare.Parse
                     , Telomare.Parse.Sugar
                     , Telomare.Possible
                     , Telomare.PossibleData
                     , Telomare.PrettyPrint
                     , Telomare.PrettyPrint.Indent
                     , Telomare.Resolve
                     , Telomare.RunTime
                     , Telomare.TypeCheck
  build-depends:       base
                     , binary
                     , bytestring
                     , containers
                     , data-fix
                     , deepseq
                     , dlist
                     , filepath
                     , megaparsec
                     , memory
                     , mtl
                     , recursion-schemes
                     , text
                     , transformers
                     , strict
                     , deriving-compat
                     , lens
                     , cryptonite
                     , utf8-string
                     , validity
                     , genvalidity
                     , free
  -- uncomment this line to get a cabal repl. Use appropiate complete path (will error with a relative path).
  -- extra-lib-dirs:      /home/hhefesto/src/telomare/lib
  default-language:    Haskell2010
  -- ghc-options:         -v3

executable telomare
  hs-source-dirs:      app
  main-is:             Main.hs
  ghc-options:         -threaded
                       -rtsopts
                       -with-rtsopts=-N
  build-depends:       base
                     , containers
                     , directory
                     , filepath
                     , optparse-applicative
                     , stm
                     , strict
                     , telomare
  default-language:    Haskell2010

executable telomare-repl
  hs-source-dirs:      app
  main-is:             Repl.hs
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  build-depends:       base
                     , containers
                     , free
                     , haskeline
                     , megaparsec
                     , mtl
                     , optparse-applicative
                     , recursion-schemes
                     , stm
                     , strict
                     , telomare
  default-language:    Haskell2010

executable telomare-evaluare
  hs-source-dirs: app
  main-is: Evaluare.hs
  ghc-options: -threaded -Wall
  build-depends:
                base,
                containers,
                free,
                mtl,
                reflex,
                reflex-vty,
                stm,
                strict,
                telomare,
                text,
                time,
                transformers,
                vty
  default-language: Haskell2010
  default-extensions:
    BangPatterns
    ConstraintKinds
    CPP
    DataKinds
    DefaultSignatures
    DeriveFunctor
    DeriveGeneric
    FlexibleContexts
    FlexibleInstances
    FunctionalDependencies
    GADTs
    GeneralizedNewtypeDeriving
    KindSignatures
    LambdaCase
    MultiParamTypeClasses
    MultiWayIf
    OverloadedStrings
    PatternGuards
    PolyKinds
    QuasiQuotes
    RankNTypes
    RecursiveDo
    ScopedTypeVariables
    StandaloneDeriving
    TemplateHaskell
    TupleSections
    TypeApplications
    TypeFamilies

executable telomare-lsp
  main-is:             LSP.hs
  hs-source-dirs:      app

  build-depends:       base
                      , containers
                      , data-fix
                      , directory
                      , filepath
                      , free
                      , lens
                      , lsp
                      , lsp-types
                      , megaparsec
                      , process
                      , stm
                      , telomare
                      , text
                      , time
                      , aeson

  default-language:    Haskell2010
  ghc-options:         -Wall
                       -threaded
                       -rtsopts
                       -with-rtsopts=-N
                       -Wunused-packages

test-suite telomare-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Spec.hs
  other-modules:       Common
  build-depends:       QuickCheck
                     , base
                     , containers
                     , data-fix
                     , dlist
                     , free
                     , hspec
                     , hspec-core
                     , mtl
                     , recursion-schemes
                     , stm
                     , strict
                     , telomare
                     , unix
  ghc-options:         -threaded
                       -rtsopts
                       -- -prof                         -- uncomment this and the following for profiling
                       -- -fprof-auto
                       -- "-with-rtsopts=-N -p -s -hT"
  default-language:    Haskell2010

test-suite telomare-parser-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             ParserTests.hs
  other-modules:       Common
  build-depends:       QuickCheck
                     , base
                     , containers
                     , data-fix
                     , free
                     , lens
                     , megaparsec
                     , mtl
                     , process
                     , recursion-schemes
                     , stm
                     , strict
                     , tasty
                     , tasty-hunit
                     , tasty-quickcheck
                     , telomare
                     , unix
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

test-suite telomare-resolver-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             ResolverTests.hs
  other-modules:       Common
                     , CaseTests
  build-depends:       Diff
                     , QuickCheck
                     , base
                     , containers
                     , data-fix
                     , free
                     , megaparsec
                     , mtl
                     , pretty-show
                     , recursion-schemes
                     , stm
                     , strict
                     , tasty
                     , tasty-hunit
                     , tasty-quickcheck
                     , telomare
                     , unix
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

test-suite telomare-sizing-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             SizingTest.hs
  other-modules:       Common
                     , RunModeTests
                     , SizingTests
  build-depends:       base
                     , bytestring
                     , containers
                     , data-fix
                     , dlist
                     , hspec
                     , hspec-core
                     , mtl
                     , recursion-schemes
                     , telomare
                     , strict
                     , QuickCheck
                     , unix
                     , free
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

test-suite telomare-udt-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             UDTTests.hs
  other-modules:       Common
                     , NatUDTTests
  build-depends:       base
                     , containers
                     , data-fix
                     , free
                     , megaparsec
                     , QuickCheck
                     , recursion-schemes
                     , strict
                     , tasty
                     , tasty-hunit
                     , tasty-quickcheck
                     , telomare
                     , unix

  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

source-repository head
  type:     git
  location: https://github.com/Stand-In-Language/stand-in-language
